config/routes.rb
NewProject::Application.routes.draw do

  root :to => 'home#index'
  resources :album_images

  resources :albums

  
  namespace :admin do
    resources :dashboards, :only => "index"
    resources :pages
    resources :album_images
    resources :albums
  end
  match "admin" => "admin/dashboards#index"
  resources :pages
  get ":permalink" => "pages#show", :as => :permalink

  get "home/about"
  get "home/contact_us"

  resources :users
  resources :sessions
  match 'logout/:id' => "sessions#destroy", :as => "logout"
  

   root :to => 'home#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/views/admin/pages/_form.html.erb
<div class="h_title">New Page</div>
  <%= form_for [:admin, @page] do |f| %>
    <%#= f.error_messages %>
    <p class="element">
      <%= f.label :title %><br />
      <%= f.text_field :title, :class=>"text"%>
    </p>
    <p class="element">
      <%= f.label :content %><br />
    <%= f.text_area :content, :class => "ckeditor" %>
    </p>
    <p class="add"><%= f.submit 'Save Page'%></p>
  <% end %>

app/views/admin/pages/edit.html.erb
<%# title "Edit Admin/Page" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", [:admin, @page] %> |
  <%= link_to "View All", admin_pages_path %>
</p>

app/views/admin/pages/index.html.erb
<%# title "Admin/Pages" %>
<h1>Set Site Pages</h1>
<div align ="right" class="new_album"><%= link_to "New Admin/Page", new_admin_page_path, :style=>"text-color:#ffffff"%></div>
<table id="insured_list" border=1 class="list_table_2">
  <tr>
    <th>Title</th>
    <th colspan=4>Actions</th>
    <!-- <th>Content</th> -->
  </tr>
  <% for page in @pages %>
    <tr>
      <td><%= page.title %></td>
      <!-- <td><%#= page.content %></td> -->
      <td class="up_img"><%= link_to "Show", [:admin, page] %></td>
      <td class="up_img"><%= link_to "Edit", edit_admin_page_path(page) %></td>
      <td class="up_img"><%= link_to "Destroy", [:admin, page], :confirm => 'Are you sure?', :method => :delete %></td>
	    <td class="up_img"><%= link_to "click here", "/#{page.title}/", :id => page.title %>
    </tr>
  <% end %>
</table>

app/views/admin/pages/new.html.erb
<%# title "New Admin/Page" %>

<%= render 'form' %>

<p class="up_img" style="margin-left:40px;"><%= link_to "Back to List", admin_pages_path %></p>

app/views/admin/pages/show.html.erb
<%# title "Admin/Page" %>

<p>
  <strong>Title:</strong>
  <%= @page.title %>
</p>
<p>
  <strong>Content:</strong>
  <%= @page.content.html_safe %>
</p>

<p>
  <%= link_to "Edit", edit_admin_page_path(@page) %> |
  <%= link_to "Destroy", [:admin, @page], :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", admin_pages_path %>
</p>