config/routes.rb
NewProject::Application.routes.draw do

  root :to => 'home#index'
  resources :album_images

  resources :albums

  
  namespace :admin do
    resources :dashboards, :only => "index"
    resources :pages
    resources :album_images
    resources :albums
  end
  match "admin" => "admin/dashboards#index"
  resources :pages
  get ":permalink" => "pages#show", :as => :permalink

  get "home/about"
  get "home/contact_us"

  resources :users
  resources :sessions
  match 'logout/:id' => "sessions#destroy", :as => "logout"
  

   root :to => 'home#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/album.rb
class Album < ActiveRecord::Base
  attr_accessible :title, :status
  has_many :album_images, :dependent => :destroy
end

app/controllers/admin/albums_controller.rb
class Admin::AlbumsController < ApplicationController
  before_filter :auth_admin
  
	layout "admin"
	def index
    @albums = Album.order("order_no ASC")
  end

  def show
    @album = Album.find(params[:id])
  end

  def new
    @album = Album.new
  end

  def create
    @album = Album.new(params[:album])
    @album.upload_date = Time.now
    @album.order_no = Album.last.blank? ? "0" : Album.last.id
		if @album.save
      redirect_to [:admin,@album], :notice => "Successfully created album."
    else
      render :action => 'new'
    end
  end

  def edit
    @album = Album.find(params[:id])
  end

  def update
    @album = Album.find(params[:id])
    if @album.update_attributes(params[:album])
      redirect_to [:admin,@album], :notice  => "Successfully updated album."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @album = Album.find(params[:id])
    @album.destroy
    redirect_to admin_albums_url, :notice => "Successfully destroyed album."
  end
	
  def change_position
    @album_1 = Album.find(params[:id])
    @album_2 = Album.find(params[:change_id])
    if !@album_1.blank? && !@album_2.blank?
      order_no_1 = @album_1.order_no
      order_no_2 = @album_2.order_no
      @album_1.order_no = order_no_2
      @album_2.order_no = order_no_1
      @album_1.save
      @album_2.save
    end
    # redirect_to :action => :index
    redirect_to admin_albums_url
  end

	def show_images
		@album = Album.find(params[:id])
		@album_images = @album.album_images.order("order_no ASC")
	end
	
	def update_caption
		
		# if !params[:capiton].nil?
			params[:caption].each do|caption|
				if !caption.last.blank?
					@album_image = AlbumImage.find(caption.first)
					# render :text => "<pre>"+ @album_image.to_yaml and return
					@album_image.update_attributes(:caption => caption.last)					
				end
				
			end
		# end
		# redirect_to :action=>'index'
    redirect_to admin_albums_url
	end

  def image_album
   @albums = Album.order("order_no ASC")
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  # before_filter :user_role_auth
	# layout 'admin'
	def index
    @albums = Album.order("order_no ASC")
  end

  def show
    @album = Album.find(params[:id])
  end

  def new
    @album = Album.new
  end

  def create
    @album = Album.new(params[:album])
    @album.upload_date = Time.now
    @album.order_no = Album.last.blank? ? "0" : Album.last.id
		if @album.save
      redirect_to @album, :notice => "Successfully created album."
    else
      render :action => 'new'
    end
  end

  def edit
    @album = Album.find(params[:id])
  end

  def update
    @album = Album.find(params[:id])
    if @album.update_attributes(params[:album])
      redirect_to @album, :notice  => "Successfully updated album."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @album = Album.find(params[:id])
    @album.destroy
    redirect_to albums_url, :notice => "Successfully destroyed album."
  end
	
  def change_position
    @album_1 = Album.find(params[:id])
    @album_2 = Album.find(params[:change_id])
    if !@album_1.blank? && !@album_2.blank?
      order_no_1 = @album_1.order_no
      order_no_2 = @album_2.order_no
      @album_1.order_no = order_no_2
      @album_2.order_no = order_no_1
      @album_1.save
      @album_2.save
    end
    redirect_to :action => :index
  end

	def show_images
		@album = Album.find(params[:id])
		@album_images = @album.album_images.order("order_no ASC")
	end
	
	def update_caption
		
		# if !params[:capiton].nil?
			params[:caption].each do|caption|
				if !caption.last.blank?
					@album_image = AlbumImage.find(caption.first)
					# render :text => "<pre>"+ @album_image.to_yaml and return
					@album_image.update_attributes(:caption => caption.last)					
				end
				
			end
		# end
		redirect_to :action=>'index'
	end

  def image_album
   @albums = Album.order("order_no ASC")
  end
end

app/views/admin/albums/_form.html.erb
<%= form_for [:admin,@album] do |f| %>
  <%#= f.error_messages %>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :status, "Show Image"%>
    Yes<%= f.radio_button :status, '1' %> 
		No<%= f.radio_button :status, '0' %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/admin/albums/edit.html.erb
<h1>Edit Album</h1>

<%= render 'form' %>

<p>
  <%= link_to "Show", [:admin,@album] %> |
  <%= link_to "View All", admin_albums_path %>
</p>

app/views/admin/albums/image_album.html.erb
<link rel="stylesheet" href="/assets/prettyPhoto.css" type="text/css" media="screen" charset="utf-8" />
<script src="/assets/jquery.prettyPhoto.js" type="text/javascript" charset="utf-8"></script>
<script type="text/javascript">
    //$(function() {
    //    $('#gallery a').lightBox();
    //});
    $(document).ready(function(){
    $("a[rel^='prettyPhoto']").prettyPhoto();
  });
    </script>

   	<style type="text/css">
	/* jQuery lightBox plugin - Gallery style */
	#gallery {
		/*background-color: #444;
		padding: 10px;
		width: 520px;*/
	}
	#gallery ul { list-style: none; }
	#gallery ul li { display: inline; }
	#gallery ul img {
		border: 5px solid #3e3e3e;
		border-width: 5px 5px 20px;
	}
	#gallery ul a:hover img {
		border: 5px solid #fff;
		border-width: 5px 5px 20px;
		color: #fff;
	}
	#gallery ul a:hover { color: #fff; }
	</style>
<h2 class="index_heading">My Gallery</h2>
<% if !@albums.blank? %>  
  <div class="main_div_video" >
    <% @albums.each_with_index do  |album,index|%>
      <% @album_images = album.album_images.order("order_no ASC") %>
      <% if !@album_images.blank? %>
        <% @album_images.each_with_index do |album_image,sub_index|%>
          <% if sub_index == 0 %>
            <div class="sub_div_video" style="height: auto;">
              <span>
                <a href= '<%= album_image.album_image %>' rel="prettyPhoto[<%=index%>]" title="<%=album_image.caption if !album_image.blank? and !album_image.caption.blank?%>"><%= image_tag album_image.album_image.url,:width=>"208",:height=>"150" %></a>
              </span>
              <div><span><%= album.title%></span></div>
            </div>
          <% else %>
            <a href= '<%= album_image.album_image %>' rel="prettyPhoto[<%=index%>]" title="<%=album_image.caption if !album_image.blank? and !album_image.caption.blank?%>"></a>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/admin/albums/index.html.erb
<h1>My List of Albums</h1>
<div align ="right" class="new_album"><%= link_to "Create a new album", new_admin_album_path %></div>

<table id="insured_list" border=1 class="list_table_2">
  <thead>
  <tr>
    <th scope="col">Title</th>
    <th scope="col">Upload Date</th>
    <th scope="col">Modify Date</th>
    <th scope="col">Image Count</th>
    <th>Position</th>
    <th>Manage Image</th>
    <th>View Album Images</th>
		
    <th colspan = "3">Action</th>
  </tr>
  </thead>
  <tbody>
  <% @albums.each_with_index do |album,index| %>
    <tr>
      <td><%= album.title %></td>
      <td><%= album.upload_date %></td>
      <td><%= album.modify_date %></td>
      <td><%= album.album_images.try(:count) %></td>
      <td>
      <%= link_to image_tag("upside_arrow.jpg",:width => '18px'),:action=>"change_position",:id=>album.id,:change_id=>@albums[index.to_i - 1].id if index.to_i != 0 %>
      &nbsp;
      <%= link_to image_tag("downside_arrow.jpg",:width => '18px'),:action=>"change_position",:id=>album.id,:change_id=> @albums[index.to_i + 1].id if !@albums[index.to_i + 1].blank?%>
    </td>
      <td class="up_img"><%= link_to "Upload Image/s", :controller => "album_images", :action => "upload", :id=> album %></td>
      <td class="up_img"><%= link_to "View Image/s", :action => "show_images", :id=> album %></td>
      <td><%= link_to image_tag("view_icon.png", :alt=>"View",:border=>"0",  :title=>"View"), [:admin,album] %></td>
      <td><%= link_to image_tag("Text-Edit-Icon.png", :alt=>"Edit",:border=>"0",  :title=>"Edit"), edit_admin_album_path(album) %></td>
      <td><%= link_to image_tag("notebook_delete.png", :alt=>"Delete",:border=>"0",  :title=>"Delete"), [:admin,album], :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<% if @albums.count > 10 %>
<div id="pager" class="pager">
  <form>
    <%= image_tag('first.png' , :class=>'first' ,:title=>"First") %>
    <%= image_tag('prev.png' , :class=>'prev' ,:title=>"Previous" ) %>
    <input type="text" class="pagedisplay"/>
    <%= image_tag('next.png' , :class=>'next',:title=>"Next" ) %>
    <%= image_tag('last.png' , :class=>'last',:title=>"Last" ) %>
    <select class="pagesize">
      <option  value="5">5 per page</option>
      <option selected="selected" value="10">10 per page</option>
      <option value="20">20 per page</option>
      
    </select>
  </form>
</div>
<% end %>

app/views/admin/albums/new.html.erb
<h1>New Album</h1>

<%= render 'form' %>

<p><%= link_to "Back", admin_albums_path %></p>

app/views/admin/albums/show.html.erb
<h1>Album</h1>

<p>
  <strong>Title:</strong>
  <%= @album.title %>
</p>
<p>
  <strong>Upload Date:</strong>
  <%= @album.upload_date %>
</p>
<p>
  <strong>Modify Date:</strong>
  <%= @album.modify_date %>
</p>
<p>
  <strong>Status:</strong>
  <%= @album.status %>
</p>
<p>
  <strong>Order:</strong>
  <%= @album.order_no %>
</p>

<p>
  <%= link_to "Edit", edit_admin_album_path(@album) %> |
  <%= link_to "Destroy", [:admin,@album], :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", admin_albums_path %>
</p>

app/views/admin/albums/show_images.html.erb
<h1>Album: <%= @album.title %></h1>
<p>
  <strong>Title:</strong>
  <%= @album.title %>
</p>
<p>
  <strong>Upload Date:</strong>
  <%= @album.upload_date %>
</p>
<p>
  <strong>Modify Date:</strong>
  <%= @album.modify_date %>
</p>
<p>
  <strong>Status:</strong>
  <%= @album.status %>
</p>
<% if !@album_images.blank? %>
	<%= form_tag :action => "update_caption", :id => @album.id%>	
	<% @position = 1..@album_images.count %>
	<% @check_no = 3 %>
	<!--<table>
		
		<%#index = 1%>
		<%# @album_images.each do |album_image|%>
					<td>
						<a href= '<%#= album_image.album_image %>' class="thickbox" ><%#= image_tag album_image.album_image.url(:small) %></a><br />
						<%#= link_to image_tag("notebook_delete.png", :alt=>"Delete",:border=>"0",  :title=>"Delete"), album_image, :confirm => 'Are you sure?', :method => :delete %>
						<%#= link_to image_tag("upside_arrow.jpg",:width => '18px'),:controller=>"album_images",:action=>"change_position",:id=>album_image.id,:change_id=>@album_images[index - 2].id if index != 1 %>
      					&nbsp;
      			<%#= link_to image_tag("downside_arrow.jpg",:width => '18px'),:controller=>"album_images",:action=>"change_position",:id=>album_image.id,:change_id=> @album_images[index].id if !@album_images[index].blank?%>
						caption<br />
						<%#= text_field_tag "caption[#{album_image.id}]", album_image.caption %>
					</td>
				<%# if index % 4 == 0 %>
					</tr><tr>
				<%# end %>
				<%# index = index + 1 %>
		<%# end %>
		</tr>
	</table>-->
	<table class="list_table_2">
	  <tr>
	    <th>Image</th>
	    <th>caption</th>
	    <th>Position</th>
	    <th>Action</th>
	  </tr>
	  <%index = 1%>
	  <% @album_images.each do |album_image|%>
	    <tr>
	      <td><%= image_tag album_image.album_image.url(:small) %></td>
	      <td><%= text_field_tag "caption[#{album_image.id}]", album_image.caption %></td>
	      <td>
	        <%= link_to image_tag("upside_arrow.jpg",:width => '18px'),:controller=>"album_images",:action=>"change_position",:id=>album_image.id,:change_id=>@album_images[index - 2].id if index != 1 %>
      		&nbsp;
      		<%= link_to image_tag("downside_arrow.jpg",:width => '18px'),:controller=>"album_images",:action=>"change_position",:id=>album_image.id,:change_id=> @album_images[index].id if !@album_images[index].blank?%>
	      </td>
	      <td><%= link_to image_tag("notebook_delete.png", :alt=>"Delete",:border=>"0",  :title=>"Delete"), album_image, :confirm => 'Are you sure?', :method => :delete %></td>
	    </tr>
	    <% index = index + 1 %>
	  <% end %>
	</table>
	<%= submit_tag "Update Caption"%>
<% end %>