config/routes.rb
NewProject::Application.routes.draw do

  root :to => 'home#index'
  resources :album_images

  resources :albums

  
  namespace :admin do
    resources :dashboards, :only => "index"
    resources :pages
    resources :album_images
    resources :albums
  end
  match "admin" => "admin/dashboards#index"
  resources :pages
  get ":permalink" => "pages#show", :as => :permalink

  get "home/about"
  get "home/contact_us"

  resources :users
  resources :sessions
  match 'logout/:id' => "sessions#destroy", :as => "logout"
  

   root :to => 'home#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/album_image.rb
class AlbumImage < ActiveRecord::Base
  attr_accessible :album_image, :album_id, :status, :upload_date, :caption
  belongs_to :album 

	# validates_attachment_presence :album_image
	has_attached_file :album_image, :content_type => ['image/jpeg', 'image/png','image/gif'],											
																			:styles => { :small=>"100x100>",
																									 :large => "800x800>",
                                                   :slider=>"1260x400>"}, 
																			 :message => "is not a valid image"

  # validates_attachment_size :album_image, :less_than => 3.megabytes 
end

app/controllers/admin/album_images_controller.rb
class Admin::AlbumImagesController < ApplicationController
 before_filter :auth_admin, :except => [:new_upload]

  layout "admin"
  def index
    @album_images = AlbumImage.all
  end

  def show
    @album_image = AlbumImage.find(params[:id])
  end

  def new
    @album_image = AlbumImage.new
  end

  def create
    @album_image = AlbumImage.new(params[:album_image])
    if @album_image.save
      redirect_to [:admin,@album_image], :notice => "Successfully created album image."
    else
      render :action => 'new'
    end
  end

  def edit
    @album_image = AlbumImage.find(params[:id])
  end

  def update
    @album_image = AlbumImage.find(params[:id])
    if @album_image.update_attributes(params[:album_image])
      redirect_to [:admin,@album_image], :notice  => "Successfully updated album image."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @album_image = AlbumImage.find(params[:id])
		@album_id = @album_image.album_id
    @album_image.destroy
    redirect_to :controller => "admin/albums",:action => "show_images",:id =>@album_id , :notice => "Successfully destroyed album image."
    # redirect_to album_images_url, :notice => "Successfully destroyed album image."
  end

  def change_position
    @album_image_1 = AlbumImage.find(params[:id])
    @album_image_2 = AlbumImage.find(params[:change_id])
    if !@album_image_1.blank? && !@album_image_2.blank?
      order_no_1 = @album_image_1.order_no
      order_no_2 = @album_image_2.order_no
      @album_image_1.order_no = order_no_2
      @album_image_2.order_no = order_no_1
      @album_image_1.save
      @album_image_2.save
    end
    redirect_to :controller => "admin/albums",:action => "show_images",:id =>@album_image_1.album_id , :notice => "Successfully updated"
  end

  
	def new_upload
		# @albumimages = AlbumImage.create(:album_id => 1)
		if !params[:files].blank?
			#render :text=>"<pre>"+ params.to_yaml and return true
			params[:files].each do|f|		
				@albumimages = AlbumImage.new(:album_image => f,:album_id=>params[:id], :status=>'1', :upload_date => Time.now)		
				@albumimages.order_no = AlbumImage.last.blank? ? "0" : AlbumImage.last.id
        @albumimages.save       
        session[:user_id] = current_user.id
			end
			# render :json => [ActiveSupport::JSON.encode({ :size => @albumimages.album_image_file_size })]
		end
		
		redirect_to :controller => "admin/albums",:action => "show_images",:id =>params[:id] , :notice => "Successfully uploaded" 
		# render :layout=>false and return
	end
end

app/controllers/album_images_controller.rb
class AlbumImagesController < ApplicationController
  # before_filter :user_role_auth
  # layout 'admin'
   # layout 'admin'
  def index
    @album_images = AlbumImage.all
  end

  def show
    @album_image = AlbumImage.find(params[:id])
  end

  def new
    @album_image = AlbumImage.new
  end

  def create
    @album_image = AlbumImage.new(params[:album_image])
    if @album_image.save
      redirect_to @album_image, :notice => "Successfully created album image."
    else
      render :action => 'new'
    end
  end

  def edit
    @album_image = AlbumImage.find(params[:id])
  end

  def update
    @album_image = AlbumImage.find(params[:id])
    if @album_image.update_attributes(params[:album_image])
      redirect_to @album_image, :notice  => "Successfully updated album image."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @album_image = AlbumImage.find(params[:id])
		@album_id = @album_image.album_id
    @album_image.destroy
    redirect_to :controller => "albums",:action => "show_images",:id =>@album_id , :notice => "Successfully destroyed album image."
    # redirect_to album_images_url, :notice => "Successfully destroyed album image."
  end

  def change_position
    @album_image_1 = AlbumImage.find(params[:id])
    @album_image_2 = AlbumImage.find(params[:change_id])
    if !@album_image_1.blank? && !@album_image_2.blank?
      order_no_1 = @album_image_1.order_no
      order_no_2 = @album_image_2.order_no
      @album_image_1.order_no = order_no_2
      @album_image_2.order_no = order_no_1
      @album_image_1.save
      @album_image_2.save
    end
    redirect_to :controller => "albums",:action => "show_images",:id =>@album_image_1.album_id , :notice => "Successfully updated"
  end

def upload
end
  
	def new_upload
		# @albumimages = AlbumImage.create(:album_id => 1)
		if !params[:files].blank?
			#render :text=>"<pre>"+ params.to_yaml and return true
			
			params[:files].each do|f|		
				@albumimages = AlbumImage.new(:album_image => f,:album_id=>params[:id], :status=>'1', :upload_date => Time.now)		
				@albumimages.order_no = AlbumImage.last.blank? ? "0" : AlbumImage.last.id
        @albumimages.save				
			end
			# render :json => [ActiveSupport::JSON.encode({ :size => @albumimages.album_image_file_size })]
		end
		
		
		# render :layout=>false and return
	end
end

app/views/album_images/_form.html.erb
<%= form_for @album_image, :html => { :multipart => true } do |f| %>
  <%#= f.error_messages %>
  <% @albums = Album.all %>
	<p>
    <%= f.label :album_id,  "Album"%>
    <%= f.collection_select :album_id, @albums, :id, :title, :include_blank => 'Select Album' %>
  </p>
	<p>
    <%= f.label :album_image %>
    <%= f.file_field :album_image %>
  </p>
	
  <p><%= f.submit %></p>
<% end %>

app/views/album_images/edit.html.erb
<h1>Edit Album Image</h1>

<%= render 'form' %>

<p>
  <%= link_to "Show", @album_image %> |
  <%= link_to "View All", album_images_path %>
</p>

app/views/album_images/index.html.erb
<h1>Album Images</h1>
<div align = "right"><%= link_to "New Album Image", new_album_image_path %></div>

<table border=0 class="list_table_2">
  <tr>
    <th>Album</th>
    <th>Album Image File Name</th>
    <th>Status</th>
    <th>Order</th>
    <th>Caption</th>
    <th>Upload Date</th>
    <th colspan = "3">Action</th>
  </tr>
  <% for album_image in @album_images %>
    <tr>
      <td><%= album_image.album_id %></td>
      <td><%= image_tag album_image.album_image.url(:small)%></td>
      <td><%= album_image.status %></td>
      <td><%= album_image.order_no %></td>
      <td><%= album_image.caption %></td>
      <td><%= album_image.upload_date %></td>
      <td><%= link_to image_tag("view_icon.png", :alt=>"View",:border=>"0",  :title=>"View"), album_image %></td>
      <td><%= link_to image_tag("Text-Edit-Icon.png", :alt=>"Edit",:border=>"0",  :title=>"Edit"), edit_album_image_path(album_image) %></td>
      <td><%= link_to image_tag("notebook_delete.png", :alt=>"Delete",:border=>"0",  :title=>"Delete"), album_image, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

app/views/album_images/new.html.erb
<h1>New Album Image</h1>

<%= render 'form' %>

<p><%= link_to "Back", album_images_path %></p>

app/views/album_images/show.html.erb
<h1>Album Image</h1>

<p>
  <strong>Album:</strong>
  <%= @album_image.album_id %>
</p>
<p>
  <strong>Album Image File Name:</strong>
  <%= image_tag @album_image.album_image.url %>
</p>
<p>
  <strong>Status:</strong>
  <%= @album_image.status %>
</p>
<p>
  <strong>Order:</strong>
  <%= @album_image.order_no %>
</p>
<p>
  <strong>Caption:</strong>
  <%= @album_image.caption %>
</p>
<p>
  <strong>Upload Date:</strong>
  <%= @album_image.upload_date %>
</p>

<p>
  <%= link_to "Edit", edit_album_image_path(@album_image) %> |
  <%= link_to "Destroy", @album_image, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", album_images_path %>
</p>

app/views/album_images/upload.html.erb
<!DOCTYPE HTML>
<!--
/*
 * jQuery File Upload Plugin Demo 6.5.1
 * https://github.com/blueimp/jQuery-File-Upload
 *
 * Copyright 2010, Sebastian Tschan
 * https://blueimp.net
 *
 * Licensed under the MIT license:
 * http://www.opensource.org/licenses/MIT
 */
-->
<html lang="en">
<head>
<meta charset="utf-8">
<title>jQuery File Upload Demo</title>
<meta name="description" content="File Upload widget with multiple file selection, drag&amp;drop support, progress bar and preview images for jQuery. Supports cross-domain, chunked and resumable file uploads. Works with any server-side platform (Google App Engine, PHP, Python, Ruby on Rails, Java, etc.) that supports standard HTML form file uploads.">
<meta name="viewport" content="width=device-width">
<!-- Bootstrap CSS Toolkit styles -->
<link rel="stylesheet" href="http://blueimp.github.com/cdn/css/bootstrap.min.css">
<!-- Generic page styles -->
<link rel="stylesheet" href="/multiupload/style.css">
<!-- Bootstrap styles for responsive website layout, supporting different screen sizes -->
<link rel="stylesheet" href="http://blueimp.github.com/cdn/css/bootstrap-responsive.min.css">
<!-- Bootstrap CSS fixes for IE6 -->
<!--[if lt IE 7]><link rel="stylesheet" href="http://blueimp.github.com/cdn/css/bootstrap-ie6.min.css"><![endif]-->
<!-- Bootstrap Image Gallery styles -->
<link rel="stylesheet" href="http://blueimp.github.com/Bootstrap-Image-Gallery/css/bootstrap-image-gallery.min.css">
<!-- CSS to style the file input field as button and adjust the Bootstrap progress bars -->
<link rel="stylesheet" href="/multiupload/jquery.fileupload-ui.css">
<!-- Shim to make HTML5 elements usable in older Internet Explorer versions -->
<!--[if lt IE 9]><script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
</head>
<body style="margin: 0 auto;background: #F4F4F4 url('bodybg.png') no-repeat scroll top center;
font-family: Arial, Helvetica, sans-serif">

<div class="container">
    <div class="page-header">
        <h1>File Upload </h1>
    </div>
    
    <br>
    <!-- The file upload form used as target for the file upload widget -->
    <%#= form_tag :controller =>"album_images", :action => "new_upload", :id => 1, :html => { :multipart => true, :id="fileupload"} do |f|%>
		<form id="fileupload" action="/album_images/new_upload/<%= params[:id]%>" method="POST" enctype="multipart/form-data">
        <!-- The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload -->
        <div class="row fileupload-buttonbar">
            <div class="span7">
                <!-- The fileinput-button span is used to style the file input field as button -->
                <span class="btn btn-success fileinput-button">
                    <i class="icon-plus icon-white"></i>
                    <span>Add files...</span>
                    <input type="file" name="files[]" multiple>
                </span>
                <button type="submit" class="btn btn-primary start">
                    <i class="icon-upload icon-white"></i>
                    <span>Start upload</span>
                </button>
                <button type="reset" class="btn btn-warning cancel">
                    <i class="icon-ban-circle icon-white"></i>
                    <span>Cancel upload</span>
                </button>
                <button type="button" class="btn btn-danger delete">
                    <i class="icon-trash icon-white"></i>
                    <span>Delete</span>
                </button>
                <input type="checkbox" class="toggle">
            </div>
            <div class="span5">
                <!-- The global progress bar -->
                <div class="progress progress-success progress-striped active fade">
                    <div class="bar" style="width:0%;"></div>
                </div>
            </div>
        </div>
        <!-- The loading indicator is shown during image processing -->
        <div class="fileupload-loading"></div>
        <br>
        <!-- The table listing the files available for upload/download -->
        <table class="table table-striped"><tbody class="files" data-toggle="modal-gallery" data-target="#modal-gallery"></tbody></table>
    </form>
		<%# end %>
    <br>
    <div class="well">
        <h3>Notes</h3><br />
        <ul>
            <!-- <li>The maximum file size for uploads in this demo is <strong>5 MB</strong> (default file size is unlimited).</li> -->
            <li>Only image files (<strong>JPG, GIF, PNG</strong>) are allowed in this demo (by default there is no file type restriction).</li>
            <li>Uploaded files will be deleted automatically after <strong>5 minutes</strong></li>
            <li>You can <strong>drag &amp; drop</strong> files from your desktop on this webpage with Google Chrome, Mozilla Firefox and Apple Safari.</li>
           
        </ul>
    </div>
</div>
<!-- modal-gallery is the modal dialog used for the image gallery -->
<div id="modal-gallery" class="modal modal-gallery hide fade">
    <div class="modal-header">
        <a class="close" data-dismiss="modal">&times;</a>
        <h3 class="modal-title"></h3>
    </div>
    <div class="modal-body"><div class="modal-image"></div></div>
    <div class="modal-footer">
        <a class="btn modal-download" target="_blank">
            <i class="icon-download"></i>
            <span>Download</span>
        </a>
        <a class="btn btn-success modal-play modal-slideshow" data-slideshow="5000">
            <i class="icon-play icon-white"></i>
            <span>Slideshow</span>
        </a>
        <a class="btn btn-info modal-prev">
            <i class="icon-arrow-left icon-white"></i>
            <span>Previous</span>
        </a>
        <a class="btn btn-primary modal-next">
            <span>Next</span>
            <i class="icon-arrow-right icon-white"></i>
        </a>
    </div>
</div>
<script>
var fileUploadErrors = {
    maxFileSize: 'File is too big',
    minFileSize: 'File is too small',
    acceptFileTypes: 'Filetype not allowed',
    maxNumberOfFiles: 'Max number of files exceeded',
    uploadedBytes: 'Uploaded bytes exceed file size',
    emptyResult: 'Empty file upload result'
};
</script>

<!-- The template to display files available for upload -->
<script id="template-upload" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-upload fade">
        <td class="preview"><span class="fade"></span></td>
        <td class="name"><span>{%=file.name%}</span></td>
        <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
        {% if (file.error) { %}
            <td class="error" colspan="2"><span class="label label-important">{%=locale.fileupload.error%}</span> {%=locale.fileupload.errors[file.error] || file.error%}</td>
        {% } else if (o.files.valid && !i) { %}
            <td>
                <div class="progress progress-success progress-striped active"><div class="bar" style="width:0%;"></div></div>
            </td>
            <td class="start">{% if (!o.options.autoUpload) { %}
                <button class="btn btn-primary">
                    <i class="icon-upload icon-white"></i>
                    <span>{%=locale.fileupload.start%}</span>
                </button>
            {% } %}</td>
        {% } else { %}
            <td colspan="2"></td>
        {% } %}
        <td class="cancel">{% if (!i) { %}
            <button class="btn btn-warning">
                <i class="icon-ban-circle icon-white"></i>
                <span>{%=locale.fileupload.cancel%}</span>
            </button>
        {% } %}</td>
    </tr>
{% } %}
</script>
<!-- The template to display files available for download -->
<script id="template-download" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-download fade">
        {% if (file.error) { %}
            <td></td>
            <td class="name"><span>{%=file.name%}</span></td>
            <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
            <!--<td class="error" colspan="2"><span class="label label-important">{%=locale.fileupload.error%}</span> {%=locale.fileupload.errors[file.error] || file.error%}</td>-->
        {% } else { %}
            <td class="preview">{% if (file.thumbnail_url) { %}
                <a href="{%=file.url%}" title="{%=file.name%}" rel="gallery" download="{%=file.name%}"><img src="{%=file.thumbnail_url%}"></a>
            {% } %}</td>
            <td class="name">
                <a href="{%=file.url%}" title="{%=file.name%}" rel="{%=file.thumbnail_url&&'gallery'%}" download="{%=file.name%}">{%=file.name%}</a>
            </td>
            <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
            <td colspan="2"></td>
        {% } %}
        <td class="delete">
            <button class="btn btn-danger" data-type="{%=file.delete_type%}" data-url="{%=file.delete_url%}">
                <i class="icon-trash icon-white"></i>
                <span>{%=locale.fileupload.destroy%}</span>
            </button>
            <input type="checkbox" name="delete" value="1">
        </td>
    </tr>
{% } %}
</script>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
<!-- The jQuery UI widget factory, can be omitted if jQuery UI is already included -->
<script src="/multiupload/jquery.ui.widget.js"></script>
<!-- The Templates plugin is included to render the upload/download listings -->
<script src="http://blueimp.github.com/JavaScript-Templates/tmpl.min.js"></script>
<!-- The Load Image plugin is included for the preview images and image resizing functionality -->
<script src="http://blueimp.github.com/JavaScript-Load-Image/load-image.min.js"></script>
<!-- The Canvas to Blob plugin is included for image resizing functionality -->
<script src="http://blueimp.github.com/JavaScript-Canvas-to-Blob/canvas-to-blob.min.js"></script>
<!-- Bootstrap JS and Bootstrap Image Gallery are not required, but included for the demo -->
<script src="http://blueimp.github.com/cdn/js/bootstrap.min.js"></script>
<script src="http://blueimp.github.com/Bootstrap-Image-Gallery/js/bootstrap-image-gallery.min.js"></script>
<!-- The Iframe Transport is required for browsers without support for XHR file uploads -->
<script src="/multiupload/jquery.iframe-transport.js"></script>
<!-- The basic File Upload plugin -->
<script src="/multiupload/jquery.fileupload.js"></script>
<!-- The File Upload image processing plugin -->
<script src="/multiupload/jquery.fileupload-ip.js"></script>
<!-- The File Upload user interface plugin -->
<script src="/multiupload/jquery.fileupload-ui.js"></script>
<!-- The localization script -->
<script src="/multiupload/locale.js"></script>
<!-- The main application script -->
<script src="/multiupload/main.js"></script>
<!-- The XDomainRequest Transport is included for cross-domain file deletion for IE8+ -->
<!--[if gte IE 8]><script src="/multiupload/jquery.xdr-transport.js"></script><![endif]-->
</body> 
</html>