config/routes.rb
NewProject::Application.routes.draw do

  root :to => 'home#index'
  resources :album_images

  resources :albums

  
  namespace :admin do
    resources :dashboards, :only => "index"
    resources :pages
    resources :album_images
    resources :albums
  end
  match "admin" => "admin/dashboards#index"
  resources :pages
  get ":permalink" => "pages#show", :as => :permalink

  get "home/about"
  get "home/contact_us"

  resources :users
  resources :sessions
  match 'logout/:id' => "sessions#destroy", :as => "logout"
  

   root :to => 'home#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/views/layouts/_admin_header.html.erb
  <div id="header">
    <div id="top">
      <div class="left">
        <p><b>Poonam Jadhwani-Admin Panel</b></p>
      </div>
      <div class="right">
        <div class="align-right">
          <p>Welcome, <strong>Admin</strong> [ <a href="<%=logout_path(current_user.id)%>">logout</a> ]</p>
        </div>
      </div>
    </div>
    <div id="nav">
      <ul>
        <li class="upp"><a href="<%=root_url%>">Home</a>
          <!-- <ul>
            <li>&#8250; <a href="">Visit site</a></li>
            <li>&#8250; <a href="">Reports</a></li>
            <li>&#8250; <a href="">Add new page</a></li>
            <li>&#8250; <a href="">Site config</a></li>
          </ul> -->
        </li>
        <li class="upp"><a href="#">Gallery</a>
          <ul>
            <li>&#8250;<%= link_to "Show Gallery", :controller=>"/admin/albums", :action=>"index" %></li>
            <li>&#8250; <a href="">Add new</a></li>
            <!-- <li>&#8250; <a href="">Add new gallery</a></li>
            <li>&#8250; <a href="">Categories</a></li> -->
          </ul>
        </li>
        <li class="upp"><a href="#">Set Pages</a>
          <ul>
            <li>&#8250; <%=link_to "Show All Pages", admin_pages_path %></li>
            <li>&#8250;<%=link_to "Add new", new_admin_page_path %></li>
            <!-- <li>&#8250; <a href="">Lock users</a></li> -->
          </ul>
        </li>
        <li class="upp"><a href="#">Settings</a>
          <ul>
            <li>&#8250; <a href="">Dummy</a></li>
            <li>&#8250; <a href="">Dummy</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>

app/views/layouts/_admin_sidebar.html.erb
<div id="sidebar">
		<div class="box">
			<div class="h_title">&#8250; Main control</div>
			<ul id="home">
				<li class="b1"><a class="icon view_page" href="">Visit site</a></li>
				<li class="b2"><a class="icon report" href="">Reports</a></li>
				<li class="b1"><a class="icon add_page" href="">Add new page</a></li>
				<li class="b2"><a class="icon config" href="">Site config</a></li>
			</ul>
		</div>
		
		<!-- <div class="box">
			<div class="h_title">&#8250; Manage content</div>
			<ul>
				<li class="b1"><a class="icon page" href="">Show all pages</a></li>
				<li class="b2"><a class="icon add_page" href="">Add new page</a></li>
				<li class="b1"><a class="icon photo" href="">Add new gallery</a></li>
				<li class="b2"><a class="icon category" href="">Categories</a></li>
			</ul>
		</div>
		<div class="box">
			<div class="h_title">&#8250; Users</div>
			<ul>
				<li class="b1"><a class="icon users" href="">Show all users</a></li>
				<li class="b2"><a class="icon add_user" href="">Add new user</a></li>
				<li class="b1"><a class="icon block_users" href="">Lock users</a></li>
			</ul>
		</div>
		<div class="box">
			<div class="h_title">&#8250; Settings</div>
			<ul>
				<li class="b1"><a class="icon config" href="">Site configuration</a></li>
				<li class="b2"><a class="icon contact" href="">Contact Form</a></li>
			</ul>
		</div> -->
	</div>

app/views/layouts/_header.html.erb
<!-- raviiiiiiiiiiiiiiiiiiiiii-->
<div class="header" style="margin-top:20px;">
	<div class="top-menu">
    <%= link_to "GALLERY", :controller=>"/albums/image_album/1", :action=>"index" %> /
  	<% if !@pages.blank?%>
      <% @pages.each_with_index do |page,i| %>
      <%if ((i + 1) == @pages.length)%>
        /
      <%end%>
        <%= link_to page.title.upcase, "/#{page.title}/", :title => page.title, :id => page.title%>
      <% end %>
    <% end %>
    <%#= link_to "GALLERY", :controller=>"/admin/albums/image_album/1", :action=>"index" %> 
    <%#= link_to "CONTACT", :controller => "/home", :action=>"contact_us" %> 
    <%#= link_to "ABOUT ME", :controller => "/home", :action=>"about" %> 
    <%#= link_to "ADMIN", :controller=>"/admin/albums", :action=>"index" %> 
    <% if current_user %>
     / <%= link_to "ADMIN", admin_dashboards_path %>
     / <%= link_to "LOGOUT", logout_path(current_user.id), :method => :delete%>
    <% end %>
  </div>
  <div class="logo"><%= link_to image_tag('poonam_logo.png'), root_url%></div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Poonam</title>
  <%= stylesheet_link_tag    "admin", :media => "all"%>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="wrap">
		<%= render 'layouts/admin_header'%>
		<div id="content">
			<%= render 'layouts/admin_sidebar'%>
			<div id="main">
				<div class="full_w">
					<%= yield %>
				</div>
			</div>
		</div>
	</div>
</body>
</html>
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Poonam</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="wrapper">
		<%= render 'layouts/header'%>
		<%#= image_tag('http://storyteller-development.s3.amazonaws.com/staticimages/photo1.png') %>
		<div class="containers">      
			<%=flash[:notice]%>
			<%= yield %>
		</div>
	</div>
</body>
</html>
 

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Poonam</title>
  <%= stylesheet_link_tag    "login", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
			<%= yield %>
</body>
</html>
 